### ISSUE TITLE
"What to do?" Open link within new screen

### ISSUE THREAD

**Issue by aaron-furtado-wwindia** [sharewater-dev/AARescue#71]
### Screen

Accident Assist

### Required

"What to do?" should open link within in-app browser

Refer image

![screen-5](https://cloud.githubusercontent.com/assets/22975829/23755304/d98c8332-0505-11e7-8708-aee3a0a1bd5d.png)

### Requested by

@sharewater-dev 

### TODO

- [ ] Open in new screen
- [ ] Screen to have "Button" to pop screen
- [ ] "Continue" Button should take user to "Location & Time" screen

**Comment by vaibhav-khot** [comment]
@sharewater-dev @evelynviljoen Please provide "What to do?" link

**Comment by sharewater-dev** [comment]
I have asked aa for details awaiting response

**Comment by aaron-furtado-wwindia** [comment]
### Information to implement

What to do

The National Road Traffic Act: Section 61 outlines the duty of a driver of a vehicle involved in an accident in which a person is killed or injured, or suffers damage to property, including a vehicle or animal:

immediately stop the vehicle and report the accident;
determine the nature and extent of any injury to any person;
if a person is injured, provide any assistance you can;
determine the nature and extent of any damage to property;
if required to do so, give your name and address, the name and address of the owner of the vehicle and the registration number of the vehicle;
if not already reported to a police or traffic officer at the scene of the accident, report the accident to any police officer at a police station as soon as possible and produce your driving licence. In the case of death or injury, this should be within 24 hours of the accident, or if no death or injury was sustained, on the first working day after the accident;
do not take any intoxicating liquor or drug, except on the instructions of a medical practitioner.
In the event of an accident in which a person is killed or injured, do not remove any vehicle from the position in which it came to rest until this has been authorised by a traffic officer, except when the accident causes complete obstruction of a public road, in which case the vehicle may be moved sufficiently to allow the passage of traffic, after its position has been clearly marked on the road by the person moving it.

In the event of an accident in which no one is killed or injured, you may not remove a vehicle from the scene of the accident without the permission of the owner, driver or operator, except to allow the passage of traffic. You should also obtain all the information you possibly can in order to support your insurance claim, or legal case if it comes to that.

Names, addresses, ID numbers, and contact details for 3rd parties is vital, as well as insurance, car registration numbers, driving and car licence details. If the driver is not the owner of the vehicle, you'll need to get the same details for the vehicle owner/s. If the vehicle is owned by a company, you'll need to record the company details too.

Photographs of damage to vehicles or other property is also a good idea to support any claims you may need to make, or answer, as well as notes regarding the extent of the damage.

For witnesses you'll need names, telephone and ID numbers, as well as a witness statement. You should record this in writing; however, a voice or video recording may be accepted by your insurer. Details of the road and weather conditions at the time of the accident, as well as visibility may substantiate your claim.

Make a note of any landmarks, as well as distances. Make a note of any police officer's details at the scene of the accident.

### Provided by

@evelynviljoen

**Comment by aaron-furtado-wwindia** [comment]
@mitul-neosoft I have updated the task description

**Comment by mitul-neosoft** [comment]
Completed
