### ISSUE TITLE
CloudBanc Document API Integration for Accident Assist (All Screens)

### ISSUE THREAD

**Issue by aaron-furtado-wwindia** [sharewater-dev/AARescue#74]
### Screen

Accident Assist

### Required

CloudBanc Document API Integration for Accident Assist (All Screens)

Refer image

![screen](https://cloud.githubusercontent.com/assets/22975829/23783755/d92490dc-0583-11e7-92ea-cee209af79ad.png)

### Requested by

@sharewater-dev 

### API Doc

[Cloudbanc Document API.docx](https://github.com/sharewater-dev/AARescue/files/833086/Cloudbanc.Document.API.docx)

### TODO

- [ ] API integration: Location & Time
- [ ] API integration: Accident Details
- [ ] API integration: Your Details
- [ ] API integration: Third Party Details
