### ISSUE TITLE
Accident Details Screen

### ISSUE THREAD

**Issue by aaron-furtado-wwindia** [sharewater-dev/AARescue#78]
### Screen

Accident Assist

### Required

Implement Screen
Add "Back" button to go to the previous screen.
"Save and Continue" to save data in respective Cloudbanc Docmument and RS web APIs then open "Your Details" Screen

### Requested by

@sharewater-dev 

### TODO

- [ ] Add back button to pop current screen
- [ ] Implement Cloudbanc Document APIs
- [ ] Implement RS APIs
- [ ] Navigate to "Your Details"
