### ISSUE TITLE
3rd Party Vehicle Details

### ISSUE THREAD

**Issue by aaron-furtado-wwindia** [sharewater-dev/AARescue#81]
### Screen

Accident Assist

### Required

Implement Screen
Add "Back" button to go to the previous screen.
"Save and Continue" to save data in respective Cloudbanc Docmument and RS web APIs then open "Saved" Screen

Refer screen

![screen](https://cloud.githubusercontent.com/assets/22975829/23786643/3fd1f238-0594-11e7-997a-c4552db8f5bf.png)

### Requested by

@sharewater-dev 

### TODO

- [ ] Add back button to pop current screen
- [ ] Implement Cloudbanc Document APIs
- [ ] Implement RS APIs
- [ ] Show "Saved Screen" for 2 seconds and navigate to "Accident Assist" main screen
- [ ] "Add another 3rd Party" button allows to have multiple third parties. Same form to be repeated

**Comment by vaibhav-khot** [comment]
We will be implementing the following colors in this build


![screen shot 2017-03-10 at 4 16 21 pm](https://cloud.githubusercontent.com/assets/22976228/23792460/0b8e6902-05ad-11e7-9858-daf40675e1b1.png)
