### ISSUE TITLE
Reminder Service Main Screen

### ISSUE THREAD

**Issue by aaron-furtado-wwindia** [sharewater-dev/AARescue#82]
### Screen

Reminder Service

### Required

Implement Dropdown and Recurring features

Refer screen

![screen](https://cloud.githubusercontent.com/assets/22975829/23790989/61acc3d4-05a7-11e7-8ae7-8b22281a577c.png)

### Requested by

@sharewater-dev 

### TODO

- [ ] Config file: "Select Reminder" List from the config file to be provided by Steven
- [ ] Other: Textfield with 200 character limit.
- [ ] If Recurring is off then reminder not to be repeated and Reminder Frequency option to be disabled
- [ ] Reminder Frequency: Daily | Weekly | Monthly | Yearly
- [ ] Calendar Plugin Integration
- [ ] Save the reminder in App and default Device calendar
