### ISSUE TITLE
Display previously added reminders (stored in app)

### ISSUE THREAD

**Issue by aaron-furtado-wwindia** [sharewater-dev/AARescue#84]
### Screen

Reminder Service (View all Reminder)

### Required

Display previously added reminders (stored in app)

Refer screen

![screen](https://cloud.githubusercontent.com/assets/22975829/23791933/fcf9b006-05aa-11e7-826b-3ae4c4b4ee75.png)

### Requested by

@sharewater-dev 

### TODO

- [ ] Config file: "Select Reminder" List from the config file to be provided by Steven
- [ ] Other: Textfield with 200 character limit.
- [ ] If Recurring is off then reminder not to be repeated and Reminder Frequency option to be disabled
- [ ] Reminder Frequency: Daily | Weekly | Monthly | Yearly
- [ ] Calendar Plugin Integration
- [ ] Save the reminder in App and default Device calendar
